# EE658/758 Machine Learning in Engineering
# Assignment #2: Logistic Regression
## Spring 2023

In [1]:
# Zachary Chou 
#1 Import libraries numpy, pandas, matplotlib.pyplot
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#2 Read the csv file 
df = pd.read_csv('bodyPerformance.csv')

print(df) 

        age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0      M      172.3      75.24        21.3       80.0     130.0   
1      25.0      M      165.0      55.80        15.7       77.0     126.0   
2      31.0      M      179.6      78.00        20.1       92.0     152.0   
3      32.0      M      174.5      71.10        18.4       76.0     147.0   
4      28.0      M      173.8      67.70        17.1       70.0     127.0   
...     ...    ...        ...        ...         ...        ...       ...   
13388  25.0      M      172.1      71.80        16.2       74.0     141.0   
13389  21.0      M      179.7      63.90        12.1       74.0     128.0   
13390  39.0      M      177.2      80.50        20.1       78.0     132.0   
13391  64.0      F      146.1      57.70        40.4       68.0     121.0   
13392  34.0      M      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm cl

In [3]:
#3 Explore the data using Panda's info() and describe() functions. Find the minimum and maximum values for each attribute. 
print(df.describe())

df.info()

age = df['age'].tolist()

height_cm = df['height_cm'].tolist()

weight_kg = df['weight_kg'].tolist()

body_fat = df['body fat_%'].tolist()

diastolic = df['diastolic'].tolist()

systolic = df['systolic'].tolist()

gripForce = df['gripForce'].tolist()

sit_and_bend_forward_cm = df['sit and bend forward_cm'].tolist()

sit_ups_counts = df['sit-ups counts'].tolist()

broad_jump_cm = df['broad jump_cm'].tolist()

print('\nThe minimum age is:',min(age))

print('The maximum age is:',max(age))

print('\nThe minimum height in cm is:',min(height_cm))

print('The maximum height in cm is:',max(height_cm))

print('\nThe minimum weight in kg is:',min(weight_kg))

print('The maximum weight in kg is:',max(weight_kg))

print('\nThe minimum body fat percentage is:',min(body_fat))

print('The maximum body fat percentage is:',max(body_fat))

print('\nThe minimum diastolic is:',min(diastolic))

print('The maximum diastolic is:',max(diastolic))

print('\nThe minimum systolic is:',min(systolic))

print('The maximum systolic is:',max(systolic))

print('\nThe minimum grip force is:',min(gripForce))

print('The maximum grip force is:',max(gripForce))

print('\nThe minimum sit and bend forward in cm is:',min(sit_and_bend_forward_cm))

print('The maximum sit and bend forward in cm is:',max(sit_and_bend_forward_cm))

print('\nThe minimum sit-ups counts is:',min(sit_ups_counts))

print('The maximum sit-ups counts is:',max(sit_ups_counts))

print('\nThe minimum board jump in cm is:',min(broad_jump_cm))

print('The maximum board jump in cm is:',max(broad_jump_cm))



                age     height_cm     weight_kg    body fat_%     diastolic  \
count  13393.000000  13393.000000  13393.000000  13393.000000  13393.000000   
mean      36.775106    168.559807     67.447316     23.240165     78.796842   
std       13.625639      8.426583     11.949666      7.256844     10.742033   
min       21.000000    125.000000     26.300000      3.000000      0.000000   
25%       25.000000    162.400000     58.200000     18.000000     71.000000   
50%       32.000000    169.200000     67.400000     22.800000     79.000000   
75%       48.000000    174.800000     75.300000     28.000000     86.000000   
max       64.000000    193.800000    138.100000     78.400000    156.200000   

           systolic     gripForce  sit and bend forward_cm  sit-ups counts  \
count  13393.000000  13393.000000             13393.000000    13393.000000   
mean     130.234817     36.963877                15.209268       39.771224   
std       14.713954     10.624864                 8.45

In [4]:
#4 Print out the unique (distinct) values for each of the attributes
# Had to remane class to classification because when using class python thinks class is being used as a keyword 
df.rename(columns = {'class':'classification'},inplace=True)

classification = df['classification'].tolist()

gender = df['gender'].tolist()

print('Classification is: \n',classification)

print('\nGender is: \n',gender)



Classification is: 
 ['C', 'A', 'C', 'B', 'B', 'B', 'D', 'B', 'C', 'B', 'A', 'D', 'C', 'C', 'C', 'A', 'C', 'A', 'B', 'B', 'C', 'A', 'D', 'B', 'C', 'C', 'D', 'D', 'C', 'A', 'C', 'C', 'A', 'D', 'B', 'C', 'D', 'A', 'A', 'D', 'D', 'D', 'C', 'C', 'A', 'D', 'B', 'D', 'A', 'B', 'A', 'A', 'C', 'B', 'D', 'B', 'C', 'C', 'D', 'D', 'C', 'D', 'C', 'A', 'B', 'D', 'B', 'D', 'B', 'A', 'D', 'C', 'A', 'C', 'D', 'D', 'B', 'D', 'B', 'B', 'D', 'A', 'B', 'A', 'B', 'B', 'C', 'A', 'A', 'A', 'C', 'A', 'A', 'B', 'B', 'A', 'C', 'C', 'B', 'D', 'C', 'D', 'A', 'D', 'D', 'A', 'D', 'B', 'A', 'C', 'B', 'A', 'C', 'A', 'B', 'C', 'B', 'C', 'A', 'B', 'B', 'A', 'A', 'D', 'A', 'D', 'D', 'B', 'C', 'A', 'A', 'C', 'C', 'D', 'A', 'A', 'D', 'B', 'C', 'D', 'C', 'C', 'B', 'B', 'D', 'C', 'B', 'C', 'B', 'C', 'A', 'D', 'A', 'D', 'C', 'B', 'C', 'B', 'C', 'C', 'B', 'A', 'D', 'B', 'B', 'A', 'B', 'B', 'A', 'C', 'C', 'A', 'A', 'C', 'A', 'B', 'B', 'C', 'C', 'A', 'A', 'B', 'B', 'C', 'A', 'C', 'B', 'D', 'A', 'D', 'A', 'B', 'A', 'D', 'A', 'B'

In [5]:
#5 Replace the attributes with categorical numerical values 
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender'] = le.fit_transform(df.gender)

le1 = LabelEncoder()
df['classification'] = le1.fit_transform(df.classification)

print(df)
print('0 = female and 1 = male \n',df.gender.value_counts())
print('\n0 = A, 1 = B, 2 = C, and 3 = D \n',df.classification.value_counts())



        age  gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0       1      172.3      75.24        21.3       80.0     130.0   
1      25.0       1      165.0      55.80        15.7       77.0     126.0   
2      31.0       1      179.6      78.00        20.1       92.0     152.0   
3      32.0       1      174.5      71.10        18.4       76.0     147.0   
4      28.0       1      173.8      67.70        17.1       70.0     127.0   
...     ...     ...        ...        ...         ...        ...       ...   
13388  25.0       1      172.1      71.80        16.2       74.0     141.0   
13389  21.0       1      179.7      63.90        12.1       74.0     128.0   
13390  39.0       1      177.2      80.50        20.1       78.0     132.0   
13391  64.0       0      146.1      57.70        40.4       68.0     121.0   
13392  34.0       1      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broa

In [6]:
#6 Define X and y Dataframes 
X = df.loc[:,['age','gender','height_cm','weight_kg','body fat_%','diastolic','systolic','gripForce','sit and bend forward_cm'
             ,'sit-ups counts','broad jump_cm']].values

y = df.loc[:,['classification']].values 

print('X data frame is \n',X)

print('\ny data frame is \n',y)

X data frame is 
 [[ 27.    1.  172.3 ...  18.4  60.  217. ]
 [ 25.    1.  165.  ...  16.3  53.  229. ]
 [ 31.    1.  179.6 ...  12.   49.  181. ]
 ...
 [ 39.    1.  177.2 ...  16.4  45.  229. ]
 [ 64.    0.  146.1 ...   9.2   0.   75. ]
 [ 34.    1.  164.  ...   7.1  51.  180. ]]

y data frame is 
 [[2]
 [0]
 [2]
 ...
 [0]
 [3]
 [2]]


In [7]:
data = pd.DataFrame(X)

X = data.to_numpy()

display(X) 

Data = pd.DataFrame(y)

y = Data.to_numpy()

display(y)

array([[ 27. ,   1. , 172.3, ...,  18.4,  60. , 217. ],
       [ 25. ,   1. , 165. , ...,  16.3,  53. , 229. ],
       [ 31. ,   1. , 179.6, ...,  12. ,  49. , 181. ],
       ...,
       [ 39. ,   1. , 177.2, ...,  16.4,  45. , 229. ],
       [ 64. ,   0. , 146.1, ...,   9.2,   0. ,  75. ],
       [ 34. ,   1. , 164. , ...,   7.1,  51. , 180. ]])

array([[2],
       [0],
       [2],
       ...,
       [0],
       [3],
       [2]])

In [8]:
#7 Normalize the data 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
y = scaler.fit_transform(y)

print('Normalized X data is \n',X)
print('\nNormalized y data is \n',y)

Normalized X data is 
 [[-0.71743212  0.76275036  0.44387298 ...  0.37731734  1.41696147
   0.67400862]
 [-0.8642197   0.76275036 -0.42246548 ...  0.12898358  0.92663372
   0.97501314]
 [-0.42385695  0.76275036  1.31021144 ... -0.37950936  0.64644644
  -0.22900492]
 ...
 [ 0.16329338  0.76275036  1.02538783 ...  0.14080899  0.36625915
   0.97501314]
 [ 1.99813815 -1.31104493 -2.66545136 ... -0.71062104 -2.7858478
  -2.88787813]
 [-0.20367558  0.76275036 -0.54114198 ... -0.9589548   0.78654008
  -0.25408863]]

Normalized y data is 
 [[ 0.44703329]
 [-1.34176769]
 [ 0.44703329]
 ...
 [-1.34176769]
 [ 1.34143378]
 [ 0.44703329]]


In [9]:
#8 Split the data into testing and training subsets  
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("X_train= \n", X_train)
print("\nX_test= \n", X_test)
print("\ny_train= \n", y_train)
print("\ny_test= \n", y_test)

X_train= 
 [[ 0.38347475  0.76275036 -1.17012744 ...  0.10533274  0.36625915
   0.44825524]
 [-0.8642197   0.76275036  0.33706413 ...  0.44826984  0.36625915
   1.05026426]
 [ 1.99813815  0.76275036 -0.57674493 ... -0.26125519 -1.38491138
  -2.11028314]
 ...
 [-0.056888    0.76275036  1.65437329 ...  0.09350733  0.43630597
   0.79942717]
 [-0.20367558  0.76275036  0.36079943 ...  0.36549192  0.22616551
  -1.7591112 ]
 [-0.13028179  0.76275036 -0.22071543 ...  0.17628525  1.48700829
   0.79942717]]

X_test= 
 [[-0.79082591  0.76275036  1.06099078 ...  0.60200026  1.41696147
   1.30110136]
 [-0.13028179  0.76275036  1.09659373 ... -0.60419229  0.36625915
   1.4014362 ]
 [-0.8642197   0.76275036  0.64562303 ...  0.40096817  1.34691465
   0.52350636]
 ...
 [ 1.63116919 -1.31104493 -1.28880394 ...  0.48374609 -1.31486456
  -1.80927862]
 [ 0.45686854  0.76275036 -0.06643598 ...  0.75573069 -0.40425588
   0.8746783 ]
 [-0.57064453  0.76275036  2.08160869 ...  0.94493736  1.20682101
   1.65227

In [13]:
#9 Using the Scikit-Learn library, train a One-Versus-One logistic regression model on the normalized training data set.
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
lr = LogisticRegression()

le = LabelEncoder()
y_train = le.fit_transform(y_train)

ovo_lr = OneVsOneClassifier(lr)

In [14]:
ovo_lr.fit(X_train, y_train)

OneVsOneClassifier(estimator=LogisticRegression())

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_test = le.fit_transform(y_test)

predictions = ovo_lr.predict(X_test)
ovo_lr.score(X_test, y_test) 

0.640119462419114

In [16]:
#10 Compute the Confusion Matrix, using the model on the testing data set 
import matplotlib.pyplot as plt
from sklearn import metrics
cm = metrics.confusion_matrix(
  y_test, predictions)
print('Confusion Martix for OnevsOne is \n',cm)

Confusion Martix for OnevsOne is 
 [[753 243  15   0]
 [222 471 263  38]
 [ 82 190 531 184]
 [ 15  44 150 817]]


In [ ]:
#11 Comment on the accuracy of your model 
# The model can predict what class a person's body performance is based on the X parameters more than half of the time.
# Not the best considering this model would be used in the health profession. Some causes can be the 
# method at which the data is normalized and the test size and random state affecting the score. 

In [17]:
#12 Using the Scikit-Learn library, train a One-Vs-Rest logistic regression model on the normalized training data
# importing the Libraries
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler = StandardScaler()
Xstd = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(Xstd, y, test_size=0.3, random_state=83)
print("X_train= \n", X_train)
print("\nX_test= \n", X_test)
print("\ny_train= \n", y_train)
print("\ny_test= \n", y_test)

X_train= 
 [[ 0.67704991  0.76275036  0.24212292 ... -0.85252605 -0.54434952
   0.17233443]
 [ 1.41098782  0.76275036  0.12344642 ...  0.53104776 -0.19411542
  -0.00325154]
 [-0.42385695  0.76275036  0.43200533 ... -0.52141437 -0.19411542
   0.24758556]
 ...
 [ 1.04401887  0.76275036 -0.26818603 ... -0.43863645 -0.33420906
  -0.50492573]
 [ 1.5577754   0.76275036  0.75243188 ... -0.43863645  0.92663372
   0.54859007]
 [-0.79082591  0.76275036  0.47947593 ...  0.23541233  0.8565869
   1.25093394]]

X_test= 
 [[-0.35046316  0.76275036  1.71371154 ...  0.66112735  0.5063528
   0.67400862]
 [ 0.97062508 -1.31104493 -1.02771564 ...  1.25239821 -0.54434952
  -0.50492573]
 [-0.57064453 -1.31104493 -0.50553903 ...  0.42461901 -0.54434952
  -0.83101395]
 ...
 [ 1.70456299 -1.31104493 -1.6329658  ...  0.05803107 -0.4743027
  -1.70894378]
 [-0.64403832  0.76275036  1.64250564 ... -1.5738765   0.08607187
   0.3479204 ]
 [ 1.77795678 -1.31104493 -1.06331859 ... -0.37950936 -1.52500502
  -1.83436233

In [18]:
# Create One-Vs-Rest Logistic Regression
ovr = LogisticRegression(random_state=15, multi_class='ovr', solver='lbfgs')

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_test = le.fit_transform(y_test)

le = LabelEncoder()
y_train = le.fit_transform(y_train)

ovr.fit(X_train, y_train)

C:\Users\choub\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(multi_class='ovr', random_state=15)

In [20]:
guess = ovr.predict(X_test)
ovr.score(X_test, y_test) 

0.60801393728223

In [21]:
#13 Compute the Confusion Matrix, using the model and testing data set 
import matplotlib.pyplot as plt
from sklearn import metrics
cm = metrics.confusion_matrix(
  y_test, guess)
print('Confusion Martix for OnevsRest is \n',cm)

Confusion Martix for OnevsRest is 
 [[839 121  29   3]
 [334 338 231  77]
 [118 204 393 295]
 [ 18  55  90 873]]


In [ ]:
#14 Compare the results of the One-Versus-One and One-Vs-Rest models 
# Both methods guess a person's body performance to the right classification more than half of the time. 
# Though, the One-Versus-One had better accuracy slightly. 

In [22]:
#15 Perform any preprocessing on the data 
# Combining class A and B to a single class. Same for class C and D
df = pd.read_csv('bodyPerformance.csv')

class_a_data = df[df['class'] == 'A']

class_b_data = df[df['class'] == 'B']

class_c_data = df[df['class'] == 'C']

class_d_data = df[df['class'] == 'D']

df_A = pd.concat([class_a_data,class_b_data],ignore_index=True)
print('The combined class A and B data frame is \n',df_A)

df_C = pd.concat([class_c_data,class_d_data],ignore_index=True)
print('The combined class C and D data frame is \n',df_C)

The combined class A and B data frame is 
        age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0     25.0      M      165.0      55.80        15.7       77.0     126.0   
1     42.0      M      169.2      65.40        19.3       63.0     110.0   
2     45.0      F      159.0      63.10        30.9       93.0     144.0   
3     26.0      M      179.9      71.50         9.7       64.0     135.0   
4     59.0      F      155.9      62.70        30.2       76.0     143.0   
...    ...    ...        ...        ...         ...        ...       ...   
6690  51.0      M      179.8      78.56        21.9       94.0     156.0   
6691  21.0      M      177.5      74.20        13.7       64.0     133.0   
6692  25.0      M      170.7      68.86        13.3       60.0     106.0   
6693  64.0      F      152.4      55.90        33.1       87.0     158.0   
6694  39.0      M      174.4      70.80        24.3       78.0     132.0   

      gripForce  sit and bend forward_cm  si

In [23]:
# Printing out the unique attributes
df_A.rename(columns = {'class':'classification'},inplace=True)

df_C.rename(columns = {'class':'group'},inplace=True)

df_C.rename(columns = {'gender':'Gender'},inplace=True)

classification = df_A['classification'].tolist()
group = df_C['group'].tolist()

gender = df_A['gender'].tolist()
Gender = df_C['Gender'].tolist()

print("Class A classification is: \n",classification)
print("\nClass C group is: \n",group)

print("\nClass A gender is: \n",gender)
print("\nClass C Gender is: \n", Gender)

Class A classification is: 
 ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 

In [24]:
# Changing the unique attributes to catagorial numerical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_A['classification'] = le.fit_transform(df_A.classification)

le1 = LabelEncoder()
df_A['gender'] = le1.fit_transform(df_A.gender)

le2 = LabelEncoder()
df_C['Gender'] = le2.fit_transform(df_C.Gender)

le3 = LabelEncoder()
df_C['group'] = le3.fit_transform(df_C.group)

print(df_A)
print('0 = female and 1 = male \n',df_A.gender.value_counts()) 
print('\n0 = A and 1 = B \n',df_A.classification.value_counts()) 
print(df_C)
print('0 = female and 1 = male \n',df_C.Gender.value_counts()) 
print('\n0 = C and 1 = D \n',df_C.group.value_counts()) 

       age  gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0     25.0       1      165.0      55.80        15.7       77.0     126.0   
1     42.0       1      169.2      65.40        19.3       63.0     110.0   
2     45.0       0      159.0      63.10        30.9       93.0     144.0   
3     26.0       1      179.9      71.50         9.7       64.0     135.0   
4     59.0       0      155.9      62.70        30.2       76.0     143.0   
...    ...     ...        ...        ...         ...        ...       ...   
6690  51.0       1      179.8      78.56        21.9       94.0     156.0   
6691  21.0       1      177.5      74.20        13.7       64.0     133.0   
6692  25.0       1      170.7      68.86        13.3       60.0     106.0   
6693  64.0       0      152.4      55.90        33.1       87.0     158.0   
6694  39.0       1      174.4      70.80        24.3       78.0     132.0   

      gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm  \


In [25]:
X = df_A.loc[:,['age','gender','height_cm','weight_kg','body fat_%','diastolic','systolic','gripForce','sit and bend forward_cm'
             ,'sit-ups counts','broad jump_cm']].values

y = df_A.loc[:,['classification']].values 

print('X data frame is \n',X)

print('\ny data frame is \n',y)

X_new = df_C.loc[:,['age','Gender','height_cm','weight_kg','body fat_%','diastolic','systolic','gripForce','sit and bend forward_cm'
             ,'sit-ups counts','broad jump_cm']].values

y_new = df_C.loc[:,['group']].values 

print('\nX_new data frame is \n',X_new)

print('\ny_new data frame is \n',y_new)

X data frame is 
 [[ 25.    1.  165.  ...  16.3  53.  229. ]
 [ 42.    1.  169.2 ...  16.   68.  211. ]
 [ 45.    0.  159.  ...  19.   30.  155. ]
 ...
 [ 25.    1.  170.7 ...  14.1  51.  235. ]
 [ 64.    0.  152.4 ...  20.   14.  154. ]
 [ 39.    1.  174.4 ...  12.   44.  168. ]]

y data frame is 
 [[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]

X_new data frame is 
 [[ 27.    1.  172.3 ...  18.4  60.  217. ]
 [ 31.    1.  179.6 ...  12.   49.  181. ]
 [ 54.    1.  166.8 ...  18.6  34.  148. ]
 ...
 [ 62.    0.  156.2 ...   5.7   1.   81. ]
 [ 21.    1.  179.7 ...   1.1  48.  167. ]
 [ 64.    0.  146.1 ...   9.2   0.   75. ]]

y_new data frame is 
 [[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [26]:
Data_A = pd.DataFrame(X)

X = Data_A.to_numpy()

display(X)  # X 

Data_A = pd.DataFrame(y)

y = Data_A.to_numpy()

display(y) # y

Data_C = pd.DataFrame(X_new)

X_new = Data_C.to_numpy()

display(X_new)  # X 

Data_C = pd.DataFrame(y_new)

y_new = Data_C.to_numpy()

display(y_new) # y

array([[ 25. ,   1. , 165. , ...,  16.3,  53. , 229. ],
       [ 42. ,   1. , 169.2, ...,  16. ,  68. , 211. ],
       [ 45. ,   0. , 159. , ...,  19. ,  30. , 155. ],
       ...,
       [ 25. ,   1. , 170.7, ...,  14.1,  51. , 235. ],
       [ 64. ,   0. , 152.4, ...,  20. ,  14. , 154. ],
       [ 39. ,   1. , 174.4, ...,  12. ,  44. , 168. ]])

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

array([[ 27. ,   1. , 172.3, ...,  18.4,  60. , 217. ],
       [ 31. ,   1. , 179.6, ...,  12. ,  49. , 181. ],
       [ 54. ,   1. , 166.8, ...,  18.6,  34. , 148. ],
       ...,
       [ 62. ,   0. , 156.2, ...,   5.7,   1. ,  81. ],
       [ 21. ,   1. , 179.7, ...,   1.1,  48. , 167. ],
       [ 64. ,   0. , 146.1, ...,   9.2,   0. ,  75. ]])

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
y = scaler.fit_transform(y)

X_new = scaler.fit_transform(X_new)
y_new = scaler.fit_transform(y_new)

print('Normalized X data is \n',X)
print('\nNormalized y data is \n',y)

print('\nNormalized X_new data is \n',X_new)
print('\nNormalized y_new data is \n',y_new)

Normalized X data is 
 [[-0.83460491  0.81421182 -0.40358122 ... -0.53354697  0.66959451
   0.8257135 ]
 [ 0.43549214  0.81421182  0.12191253 ... -0.58468607  1.96460176
   0.32964299]
 [ 0.65962691 -1.22818163 -1.15428659 ... -0.07329505 -1.31608328
  -1.21368748]
 ...
 [-0.83460491  0.81421182  0.30958887 ... -0.90856705  0.49692687
   0.99107034]
 [ 2.07914714 -1.22818163 -1.98006249 ...  0.09716862 -2.69742434
  -1.24124695]
 [ 0.21135736  0.81421182  0.77252385 ... -1.26654077 -0.10740984
  -0.85541434]]

Normalized y data is 
 [[-0.99985065]
 [-0.99985065]
 [-0.99985065]
 ...
 [ 1.00014938]
 [ 1.00014938]
 [ 1.00014938]]

Normalized X_new data is 
 [[-0.75020091  0.71289471  0.38592361 ...  0.86731347  1.75858415
   0.86684483]
 [-0.46107604  0.71289471  1.21302794 ...  0.11817108  1.00586002
  -0.00543711]
 [ 1.20139196  0.71289471 -0.23723719 ...  0.89072417 -0.02058197
  -0.80502889]
 ...
 [ 1.7796417  -1.40273169 -1.43823801 ... -0.61926596 -2.27875434
  -2.42844251]
 [-1.183

In [28]:
#16 Split the data into testing and training subsets 
from sklearn.model_selection import train_test_split
X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X_new, y_new, test_size=0.3, random_state=0)

print("X_new_train= \n", X_new_train)
print("\nX_new_test= \n", X_new_test)
print("\ny_new_train= \n", y_new_train)
print("\ny_new_test= \n", y_new_test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("\nX_train= \n", X_train)
print("\nX_test= \n", X_test)
print("\ny_train= \n", y_train)
print("\ny_test= \n", y_test)

X_new_train= 
 [[-0.38879482 -1.40273169  0.18198007 ...  1.07800977  0.0478475
  -1.55616057]
 [ 0.1171737   0.71289471  0.69183891 ... -1.0523639  -0.08901143
   0.79415467]
 [-1.11160699  0.71289471  0.35193302 ... -1.01724785  1.41643682
   0.30955359]
 ...
 [ 1.05682953  0.71289471 -0.95103956 ...  0.39909948 -0.22587036
   0.043023  ]
 [-1.18388821  0.71289471  0.94110323 ... -0.01058777  1.34800735
   1.35144591]
 [ 1.56279805  0.71289471  0.52188596 ...  0.80878672  1.00586002
   0.40647381]]

X_new_test= 
 [[ 1.7796417  -1.40273169 -1.31360585 ...  0.29375133 -0.29429983
  -1.1200196 ]
 [ 1.92420414 -1.40273169 -2.25401214 ... -0.35004291 -1.52603022
  -2.16191192]
 [-0.67791969  0.71289471  0.99775421 ...  0.78537602  0.38999483
   1.35144591]
 ...
 [-1.18388821  0.71289471  1.22435814 ...  0.01282293  0.38999483
   1.10914537]
 [ 0.98454831 -1.40273169 -1.64218154 ...  0.63320648 -0.97859449
  -0.92617916]
 [-0.24423238  0.71289471  1.6435754  ...  0.14158178  1.69015468
   

In [39]:
#17 Use the Python implementation developed in class to train a model as a binary classification problem
from sklearn.metrics import accuracy_score, f1_score, precision_score,\
recall_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
Lr = LogisticRegression()

In [51]:
# Obtain binary classification report for both of the new classes with the accuracy, F1 score, precision, and recall 
le = LabelEncoder()
y_train = le.fit_transform(y_train)

Lr.fit(X_train,y_train)

y_pred = Lr.predict(X_test)

Lr.fit(X_new_train,y_new_train)

y_new_pred = Lr.predict(X_new_test)

print('Accuracy:', accuracy_score(y_new_test, y_new_pred))
print('Accuracy:', accuracy_score(y_test, y_pred))

print('\nF1 Score:', f1_score(y_new_test, y_new_pred, average="binary"))
print('F1 Score:', f1_score(y_test, y_pred, average="binary"))

print('\nPrecision:', precision_score(y_new_test, y_new_pred, average="binary"))
print('Precision:', precision_score(y_test, y_pred, average="binary"))

print('\nRecall:', recall_score(y_new_test, y_new_pred, average="binary")) 
print('Recall:', recall_score(y_test, y_pred, average="binary")) 

print('\nClassification Report:\n', classification_report(y_new_test, y_new_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 0.7940298507462686
Accuracy: 0.7655550024888004

F1 Score: 0.7900608519269778
F1 Score: 0.7641462193289935

Precision: 0.8278427205100957
Precision: 0.7865979381443299

Recall: 0.7555771096023278
Recall: 0.7429406037000974

Classification Report:
               precision    recall  f1-score   support

        -1.0       0.76      0.83      0.80       979
         1.0       0.83      0.76      0.79      1031

    accuracy                           0.79      2010
   macro avg       0.80      0.80      0.79      2010
weighted avg       0.80      0.79      0.79      2010

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.79      0.77       982
           1       0.79      0.74      0.76      1027

    accuracy                           0.77      2009
   macro avg       0.77      0.77      0.77      2009
weighted avg       0.77      0.77      0.77      2009



C:\Users\choub\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
#18 Compute the Confusion Matrix, using the model on the testing data set 
print('Confusion Matrix for A:\n', confusion_matrix(y_test, y_pred))
print('Confusion Matrix for C:\n', confusion_matrix(y_new_test, y_new_pred))

Confusion Matrix for A:
 [[775 207]
 [264 763]]
Confusion Matrix for C:
 [[817 162]
 [252 779]]


## DUE DATE: Thursday, March, 2, 2023